spring:
  cloud:
    bus:
      refresh:
        enabled: true
      env:
        enabled: true

  kafka:
    bootstrap-servers:  localhost:9092

management:
  tracing:
    sampling:
      probability: 0.1
  endpoints:
    web:
      exposure:
        include: "*"

service:
  name: employee-27

server:
  port: 8095
